version: '3.1'

services:

  postgres:
    image: postgres:15
    container_name: c2vocab-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_DB: c2vocab
      PGDATA: /var/lib/postgres/data
    ports:
      - 5432:5432
    volumes:
      - ~/c2vocab/postgres/data:/var/lib/postgres/data
    networks:
      dc-network:
        ipv4_address: 192.168.144.12

  pgadmin:
    image: dpage/pgadmin4
    container_name: c2vocab-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "$PGADMIN_DEFAULT_EMAIL"
      PGADMIN_DEFAULT_PASSWORD: "$PGADMIN_DEFAULT_PASSWORD"
    ports:
      - 8080:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      dc-network:
        ipv4_address: 192.168.144.13

  back-end:
    build: .
    container_name: c2vocab-back-end
    restart: always
    environment:
      TELEGRAM_APITOKEN: "$TELEGRAM_APITOKEN"
      POSTGRES_CONN_STRING: "$POSTGRES_CONN_STRING"
    depends_on:
      - postgres
    networks:
      dc-network:
        ipv4_address: 192.168.144.11

volumes:
  pgadmin_data:

networks:
  dc-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.144.0/24
#          aux_addresses:
#            back-end: 192.168.144.1
#            postgres: 192.168.144.2
#            pgadmin: 192.168.144.3
