log_level:                  -4
tg_bot_upds_offset:         0
tg_bot_upds_timeout:        30
max_event_handlers:         10
max_task_handlers:          2
task_waiting_time:          1000
task_batch_size:            10
time_for_reassign:          600
lock_attempts_amount:       50
time_for_next_lock_attempt: 100